title: Canto Identity Protocol Docs
description: Developer documentation for Canto Identity Protocol
theme: just-the-docs

url: https://tster.github.io/cid-docs-pages

aux_links:
  Template Repository: https://github.com/tster/cid-docs-pages