title: Canto Identity Protocol Docs
description: Developer documentation for Canto Identity Protocol
remote_theme: just-the-docs/just-the-docs

url: https://tster.github.io/cid-docs-pages

aux_links:
  CID Repo: https://github.com/mkt-market/canto-identity-protocol
  Docs Repo: https://github.com/tster/cid-docs-pages